#include <iostream>
#include "utils/Vector3D.h"

int main() {
    freopen("test.ppm", "w", stdout);

    const int width = 255, height = 255;

    std::cout << "P3" << std::endl
        << "# This is an image in PPM format\n"
           "# Generated by DarcJC" << std::endl
        << width << ' ' << height << std::endl
        << "255" << std::endl;

    for (int i=0; i<height; ++i) { // line scan
        std::cerr << "\rScanning remaining: " << i << ' ' << std::flush;
        for (int j=0; j<width; ++j) {
            Color color(double(i) / height, double (j) / width, 0.25);
            color.write_color(std::cout);
        }
    }
    std::cerr << "\nDone.\n";

    fclose(stdin);

    return 0;
}
